#!/bin/python3

import math
import os
import random
import re
import sys

# se for impar 'weird'
# se for par entre 2 e 5 'not weird'
# se for par entre 6 e 20 'weird'
# se for par > 20 'not weird'

if __name__ == '__main__':
    n = int(input().strip())
    if n % 2 == 1: 
        print('Weird')
    elif n in range(2,5) and n % 2 == 0:
        print('Not Weird')
    elif n in range(6,21) and n % 2 == 0:
        print('Weird')
    elif n > 20:
        print('Not Weird')
